---
AWSTemplateFormatVersion: '2010-09-09'

Description: Create a certificate linked to our domain in Route 53

Resources:
  DomainCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Sub [ '*.${dnsDomain}', dnsDomain: !ImportValue DnsDomain ]
      ValidationMethod: DNS

Outputs:
  DomainCertificateArn:
    Description: 'ARN of DomainCertificate'
    Value: !Ref DomainCertificate
    Export:
      Name: DomainCertificateArn
