---
AWSTemplateFormatVersion: '2010-09-09'

Description: EC2 Access Via SSM

Resources:
  Ec2AccessViaSsmRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: 'Role for SSM - add to EC2 instance (via InstanceProfile) if SSM access is needed'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'

  Ec2AccessViaSsmPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: 'Policy for SSM'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 'ssm:UpdateInstanceInformation'
              - 'ssmmessages:CreateControlChannel'
              - 'ssmmessages:CreateDataChannel'
              - 'ssmmessages:OpenControlChannel'
              - 'ssmmessages:OpenDataChannel'
            Resource: '*'
          - Effect: 'Allow'
            Action:
              - 's3:GetEncryptionConfiguration'
            Resource: '*'
      Roles:
        - !Ref Ec2AccessViaSsmRole

  Ec2AccessViaSsmInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref Ec2AccessViaSsmRole

  Ec2AccessViaSsmSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: 'ec2-access-via-ssm'
      GroupDescription: 'Allow SSM to reach AWS API - add to EC2 instance if SSM access is needed'
      VpcId: !ImportValue Vpc
      SecurityGroupEgress:
        - IpProtocol: 'tcp'
          FromPort: 443
          ToPort: 443
          CidrIp: '0.0.0.0/0'
          Description: 'Traffic to HTTPS anywhere without Proxy'
      Tags:
        - Key: 'Name'
          Value: 'ec2-access-via-ssm'

Outputs:
  Ec2AccessViaSsmInstanceProfileArn:
    Value: !GetAtt Ec2AccessViaSsmInstanceProfile.Arn
    Export:
      Name: Ec2AccessViaSsmInstanceProfileArn
  Ec2AccessViaSsmSecurityGroup:
    Value: !Ref Ec2AccessViaSsmSecurityGroup
    Export:
      Name: Ec2AccessViaSsmSecurityGroup
  Ec2AccessViaSsmPolicyArn:
    Value: !Ref Ec2AccessViaSsmPolicy
    Export:
      Name: Ec2AccessViaSsmPolicyArn
