---
AWSTemplateFormatVersion: '2010-09-09'

Description: EKS Nodegroup.

Parameters:
  EksClusterNameParam:
    Type: 'String'
    MinLength: 1
  NodeInstanceTypesParam:
    Type: 'String'
    MinLength: 1
    Description: 'EC2 instance types for provisioning - see https://docs.aws.amazon.com/eks/latest/userguide/choosing-instance-type.html'
    Default: 'm5.2xlarge,m5.4xlarge '
  MaxScalingSizeParam:
    Type: 'String'
    Default: '75'
    Description: Max scaling size for EKS worker node group
  SubnetIdParam:
    Type: 'String'
    MinLength: 1
  CapacityTypeParam:
    Type: 'String'
    AllowedValues:
    - 'ON_DEMAND'
    - 'SPOT'
    Default: 'SPOT'

Resources:

  EKSWorkerNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      NodegroupName: !Sub '${AWS::StackName}'
      ClusterName: !Ref EksClusterNameParam
      CapacityType: !Ref CapacityTypeParam
      InstanceTypes: !Split [ ",", !Ref NodeInstanceTypesParam ]
      NodeRole: !ImportValue EksNodeInstanceRoleArn
      LaunchTemplate:
        Id: !ImportValue EksNodeLaunchTemplate
        Version: !ImportValue EksNodeLaunchTemplateLatestVersion
      ScalingConfig:
        MinSize: 0
        DesiredSize: 1
        MaxSize: !Ref MaxScalingSizeParam
      Subnets:
      - !Ref SubnetIdParam