
AWSTemplateFormatVersion: "2010-09-09"

Description: A simple test to validate localstack handling of conditions

Parameters:
  SsmParameterNameParam:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: AWS SSM parameter of the AMI ID for the EKS Node Instances. Change this value to match the version of Kubernetes you are using. Refer to https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html
    Default: 'test1'
  SsmParameterValueOverrideParam:
    Type: 'String'
    Description: 'If this value is supplied, it will override SsmParameterNameParam'
    Default: 'not-set'

Conditions:
  UseSsmParameterValueCondition: !Equals [!Ref SsmParameterValueOverrideParam, 'not-set']

Resources:

  SecretData: 
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete 
    Properties:
      Description: 'What did we select?'
      Name: !Sub '${AWS::StackName}-LocalstackCloudFormationTest'
      SecretString: !If [UseSsmParameterValueCondition, !Ref SsmParameterNameParam, !Ref SsmParameterValueOverrideParam]
            
Outputs:

  SecretDataArn:
    Value: !Ref SecretData
    Export:
      Name: !Sub '${AWS::StackName}-SecretDataArn'