---
AWSTemplateFormatVersion: '2010-09-09'

Description: Private VPC CIDR for EKS deployed in a VPC with a limited size CIDR

Parameters:
  SecondaryCidrParam:
    Type: 'String'
    AllowedPattern: '100\.\d{1,3}\.0\.0/16'
    Default: '100.64.0.0/16'
    Description: 'Additional VPC CIDR from the range 100.64.0.0/16 - 100.127.0.0/16'
  SubnetAz1CidrParam:
    Type: 'String'
    AllowedPattern: '100\.\d{1,3}\.\d{1,3}\.0/\d\d'
    Default: '100.64.0.0/18'
  SubnetAz2CidrParam:
    Type: 'String'
    AllowedPattern: '100\.\d{1,3}\.\d{1,3}\.0/\d\d'
    Default: '100.64.64.0/18'
  SubnetAz3CidrParam:
    Type: 'String'
    AllowedPattern: '100\.\d{1,3}\.\d{1,3}\.0/\d\d'
    Default: '100.64.128.0/18'
  SubnetNamePrefixParam:
    Type: 'String'
    MinLength: 1
    Default: 'vpc_eks_'

Resources:
  PrivateVpcCidrBlock:
    Type: 'AWS::EC2::VPCCidrBlock'
    Properties:
      VpcId: !ImportValue Vpc
      CidrBlock: !Ref SecondaryCidrParam

  EksNodeRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !ImportValue Vpc
      Tags:
        - Key: 'Name'
          Value: 'eks_node_route_table'

  SubnetEksNodesAz1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref SubnetAz1CidrParam
      MapPublicIpOnLaunch: False
      VpcId: !ImportValue Vpc
      Tags:
        - Key: 'Name'
          Value: !Sub '${SubnetNamePrefixParam}_az1'
  NetworkAclSubnetEksNodesAz1:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !ImportValue NetworkAcl
      SubnetId: !Ref SubnetEksNodesAz1
  RouteTableSubnetEksNodesAz1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref EksNodeRouteTable
      SubnetId: !Ref SubnetEksNodesAz1

  SubnetEksNodesAz2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref SubnetAz2CidrParam
      MapPublicIpOnLaunch: False
      VpcId: !ImportValue Vpc
      Tags:
        - Key: 'Name'
          Value: !Sub '${SubnetNamePrefixParam}_az2'
  NetworkAclSubnetEksNodesAz2:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !ImportValue NetworkAcl
      SubnetId: !Ref SubnetEksNodesAz2
  RouteTableSubnetEksNodesAz2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref EksNodeRouteTable
      SubnetId: !Ref SubnetEksNodesAz2

  SubnetEksNodesAz3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: !Ref SubnetAz3CidrParam
      MapPublicIpOnLaunch: False
      VpcId: !ImportValue Vpc
      Tags:
        - Key: 'Name'
          Value: !Sub '${SubnetNamePrefixParam}_az3'
  NetworkAclSubnetEksNodesAz3:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !ImportValue NetworkAcl
      SubnetId: !Ref SubnetEksNodesAz3
  RouteTableSubnetEksNodesAz3:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref EksNodeRouteTable
      SubnetId: !Ref SubnetEksNodesAz3

  NetworkAclAllowPrivateVpcIngress:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !ImportValue NetworkAcl
      Egress: False
      RuleAction: 'allow'
      RuleNumber: 200
      Protocol: '-1'
      CidrBlock: !Ref SecondaryCidrParam
  NetworkAclAllowPrivateVpcEgress:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !ImportValue NetworkAcl
      Egress: True
      RuleAction: 'allow'
      RuleNumber: 200
      Protocol: '-1'
      CidrBlock: !Ref SecondaryCidrParam

Outputs:
  PrivateVpcCidr:
    Value: !Ref SecondaryCidrParam
    Export:
      Name: PrivateVpcCidr
  PrivateVpcCidrBlock:
    Value: !Ref PrivateVpcCidrBlock
    Export:
      Name: PrivateVpcCidrBlock
  EksNodeRouteTable:
    Value: !Ref EksNodeRouteTable
    Export:
      Name: EksNodeRouteTable
  SubnetEksNodesAz1:
    Value: !Ref SubnetEksNodesAz1
    Export:
      Name: SubnetEksNodesAz1
  SubnetEksNodesAz2:
    Value: !Ref SubnetEksNodesAz2
    Export:
      Name: SubnetEksNodesAz2
  SubnetEksNodesAz3:
    Value: !Ref SubnetEksNodesAz3
    Export:
      Name: SubnetEksNodesAz3
