---
AWSTemplateFormatVersion: '2010-09-09'

Description: Define a VPC endpoint, which is required in a private VPC to communicate with the AWS APIs

Parameters:
  ServiceEndpointNameParam:
    Type: 'String'
    Description: 'AWS Documentation: https://docs.aws.amazon.com/whitepapers/latest/aws-privatelink/what-are-vpc-endpoints.html'

Resources:

  FsxVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !ImportValue ClusterGeneralSecurityGroupId
      ServiceName: 
        !Sub 
          - "com.amazonaws.${AWS::Region}.${service}"
          - service: !Ref ServiceEndpointNameParam
      SubnetIds:
        - !ImportValue SubnetMainAz1
        - !ImportValue SubnetMainAz2
        - !ImportValue SubnetMainAz3
      VpcEndpointType: Interface
      VpcId:
        Fn::ImportValue: Vpc

