---
AWSTemplateFormatVersion: '2010-09-09'

Description: Define a VPC endpoint, which is required in a private VPC to communicate with the AWS APIs

Parameters:
  ServiceEndpointNameParam:
    Type: 'String'
    Description: 'AWS Documentation: https://docs.aws.amazon.com/whitepapers/latest/aws-privatelink/what-are-vpc-endpoints.html'

Resources:

  GatewayTypeVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "*"
            Resource:
              - arn:aws:s3:::prod-eu-central-1-starport-layer-bucket/*
              - "*"
      RouteTableIds:
        - Fn::ImportValue: RouteTable
        - Fn::ImportValue: EksNodeRouteTable
      ServiceName: 
        !Sub 
          - "com.amazonaws.${AWS::Region}.${service}"
          - service: !Ref ServiceEndpointNameParam
      VpcEndpointType: Gateway
      VpcId:
        Fn::ImportValue: Vpc


